In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel(r"C:\Users\DELL\Desktop\EDA_Practice\Rawdata.xlsx")
df

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [4]:
df["Name"]

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

In [5]:
df["Domain"]

0     Datascience#$
1           Testing
2    Dataanalyst^^#
3       Ana^^lytics
4        Statistics
5               NLP
Name: Domain, dtype: object

In [6]:
df["Age"]

0    34 years
1      45' yr
2         NaN
3         NaN
4       67-yr
5        55yr
Name: Age, dtype: object

In [7]:
df["Location"]

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

In [8]:
df["Salary"]

0     5^00#0
1    10%%000
2    1$5%000
3     2000^0
4     30000-
5    6000^$0
Name: Salary, dtype: object

In [9]:
df["Exp"]

0         2+
1         <3
2     4> yrs
3        NaN
4    5+ year
5        10+
Name: Exp, dtype: object

In [10]:
df.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [11]:
len(df["Name"])

6

In [12]:
len(df)

6

In [13]:
df.size

36

In [14]:
df.shape

(6, 6)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [16]:
df

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [19]:
df["Name"] = df["Name"].str.replace(r"\W","",regex = True)
df["Name"]

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: object

In [20]:
df["Domain"] = df["Domain"].str.replace(r"\W", "", regex = True)
df["Domain"]

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: object

In [21]:
df["Age"] = df["Age"].str.replace(r"\W", "", regex = True)
df["Age"]

0    34years
1       45yr
2        NaN
3        NaN
4       67yr
5       55yr
Name: Age, dtype: object

In [22]:
df["Age"] = df["Age"].str.extract("(\d+)")
df["Age"]

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [23]:
df["Location"] = df["Location"].str.replace(r"\W", "", regex = True)
df["Location"]

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

In [25]:
df["Exp"] = df["Exp"].str.extract("(\d+)")
df["Exp"]

0      2
1      3
2      4
3    NaN
4      5
5     10
Name: Exp, dtype: object

In [26]:
df

    Name       Domain  Age   Location   Salary  Exp
0   Mike  Datascience   34     Mumbai   5^00#0    2
1  Teddy      Testing   45  Bangalore  10%%000    3
2   Umar  Dataanalyst  NaN        NaN  1$5%000    4
3   Jane    Analytics  NaN   Hyderbad   2000^0  NaN
4  Uttam   Statistics   67        NaN   30000-    5
5    Kim          NLP   55      Delhi  6000^$0   10

In [27]:
df["Age"] = df["Age"].fillna(np.mean(pd.to_numeric(df["Age"])))
df["Age"]

0       34
1       45
2    50.25
3    50.25
4       67
5       55
Name: Age, dtype: object

In [28]:
df

    Name       Domain    Age   Location   Salary  Exp
0   Mike  Datascience     34     Mumbai   5^00#0    2
1  Teddy      Testing     45  Bangalore  10%%000    3
2   Umar  Dataanalyst  50.25        NaN  1$5%000    4
3   Jane    Analytics  50.25   Hyderbad   2000^0  NaN
4  Uttam   Statistics     67        NaN   30000-    5
5    Kim          NLP     55      Delhi  6000^$0   10

In [29]:
df["Exp"] = df["Exp"].fillna(np.mean(pd.to_numeric(df["Exp"])))
df["Exp"]

0      2
1      3
2      4
3    4.8
4      5
5     10
Name: Exp, dtype: object

In [30]:
df["Salary"] = df["Salary"].str.replace(r"\W","", regex = True)
df["Salary"]

0     5000
1    10000
2    15000
3    20000
4    30000
5    60000
Name: Salary, dtype: object

In [31]:
df

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25        NaN  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [32]:
df["Location"] = df["Location"].fillna(df["Location"].mode()[0])
df["Location"]

0       Mumbai
1    Bangalore
2    Bangalore
3     Hyderbad
4    Bangalore
5        Delhi
Name: Location, dtype: object

In [33]:
df

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25  Bangalore  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [34]:
dataset = df.copy()
dataset

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25  Bangalore  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [35]:
dataset

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25  Bangalore  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [36]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      object
 3   Location  6 non-null      object
 4   Salary    6 non-null      object
 5   Exp       6 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [37]:
dataset["Name"] = dataset["Name"].astype("category")

In [38]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      object
 2   Age       6 non-null      object
 3   Location  6 non-null      object
 4   Salary    6 non-null      object
 5   Exp       6 non-null      object
dtypes: category(1), object(5)
memory usage: 598.0+ bytes

In [39]:
dataset["Domain"] = dataset["Domain"].astype("category")

In [40]:
dataset["Age"] = dataset["Age"].astype("int")

In [41]:
dataset["Location"] = dataset["Location"].astype("category")

In [42]:
dataset["Salary"] = dataset["Salary"].astype("int")

In [43]:
dataset["Exp"] = dataset["Exp"].astype("int")

In [44]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      category
 2   Age       6 non-null      int64
 3   Location  6 non-null      category
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      int64
dtypes: category(3), int64(3)
memory usage: 938.0 bytes

In [45]:
dataset.to_csv("dataset.csv")

In [46]:
import os
os.getcwd()

'C:\\Users\\DELL\\Desktop\\EDA_Practice'

In [50]:
plt.plot(x,y)
xlabel("Salary")
ylabel("Exp")
plt.show()

NameError: name 'x' is not defined